name: releasable
on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - reopened
  workflow_dispatch:
jobs:
  releasable:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: check releasable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          script/bindown install -q semver-next
          bin/semver-next "$GITHUB_REPOSITORY" -r "$GITHUB_SHA" --require-labels
